# Generated by Django 6.0.3 on 2026-04-02 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("incidents", "0001_initial"),
        ("model_configs", "0001_initial"),
        ("prompts", "0001_initial"),
        ("systems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_eval", "Pending eval"),
                            ("eval_failed", "Eval failed"),
                            ("pending_approval", "Pending approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("active", "Active"),
                            ("rolled_back", "Rolled back"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("eval_dataset_ids", models.JSONField(default=list)),
                ("config_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "ai_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_candidates",
                        to="systems.aisystem",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_release_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_candidates",
                        to="model_configs.modelconfig",
                    ),
                ),
                (
                    "prompt_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_candidates",
                        to="prompts.promptversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromotionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ai_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_events",
                        to="systems.aisystem",
                    ),
                ),
                (
                    "promoted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotion_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_active_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by_promotions",
                        to="releases.releasecandidate",
                    ),
                ),
                (
                    "release_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotion_events",
                        to="releases.releasecandidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RollbackRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("incident_response", "Incident response"),
                            ("manual_revert", "Manual revert"),
                            ("budget_breach", "Budget breach"),
                            ("latency_breach", "Latency breach"),
                            ("quality_regression", "Quality regression"),
                        ],
                        max_length=50,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ai_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollback_records",
                        to="systems.aisystem",
                    ),
                ),
                (
                    "from_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rollback_from_records",
                        to="releases.releasecandidate",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rollback_records",
                        to="incidents.incident",
                    ),
                ),
                (
                    "rolled_back_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rollback_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rollback_to_records",
                        to="releases.releasecandidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
