# Generated by Django 6.0.3 on 2026-04-02 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("evals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_name", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                ("prompt_version", models.CharField(max_length=100)),
                ("latency_ms", models.PositiveIntegerField()),
                ("input_token_estimate", models.PositiveIntegerField(default=0)),
                ("output_token_estimate", models.PositiveIntegerField(default=0)),
                (
                    "cost_estimate",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("fallback_used", "Fallback used"),
                            ("timeout", "Timeout"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "eval_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="evals.evalrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
