# Generated by Django 6.0.3 on 2026-04-02 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approvals", "0001_initial"),
        ("releases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrecord",
            name="release_candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_records",
                to="releases.releasecandidate",
            ),
        ),
        migrations.AddField(
            model_name="approvalrecord",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approval_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrecord",
            index=models.Index(
                fields=["approval_type", "decision", "created_at"],
                name="approvals_a_approva_32710b_idx",
            ),
        ),
    ]
