# Generated by Django 6.0.3 on 2026-04-02 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0002_initial"),
        ("releases", "0002_alter_releasecandidate_eval_dataset_ids"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approvalrecord",
            options={"ordering": ["release_candidate_id", "approval_type"]},
        ),
        migrations.AddField(
            model_name="approvalrecord",
            name="decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="approvalrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="approvalrecord",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approval_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="approvalrecord",
            unique_together={("release_candidate", "approval_type")},
        ),
        migrations.AddIndex(
            model_name="approvalrecord",
            index=models.Index(
                fields=["release_candidate", "decision", "approval_type"],
                name="approvals_a_release_fc64c9_idx",
            ),
        ),
    ]
