# Generated by Django 6.0.3 on 2026-04-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=100)),
                ("entity_id", models.CharField(max_length=100)),
                ("event_type", models.CharField(max_length=100)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("system", "System"),
                            ("task", "Task"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actor_id", models.CharField(blank=True, max_length=100)),
                ("payload", models.JSONField(default=dict)),
                ("correlation_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "event_type", "created_at"],
                        name="audits_audi_entity__1e538a_idx",
                    ),
                    models.Index(
                        fields=["actor_type", "created_at"],
                        name="audits_audi_actor_t_a745d3_idx",
                    ),
                ],
            },
        ),
    ]
