# Generated by Django 6.0.3 on 2026-04-02 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("systems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_label", models.CharField(max_length=100)),
                ("provider_name", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                (
                    "temperature",
                    models.DecimalField(decimal_places=2, default=0.2, max_digits=4),
                ),
                ("max_tokens", models.PositiveIntegerField(default=512)),
                (
                    "top_p",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
                ("timeout_ms", models.PositiveIntegerField(default=2500)),
                ("routing_policy", models.JSONField(default=dict)),
                ("fallback_policy", models.JSONField(default=dict)),
                (
                    "cost_budget_per_run",
                    models.DecimalField(decimal_places=4, default=0.02, max_digits=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("candidate", "Candidate"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ai_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_configs",
                        to="systems.aisystem",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_model_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["ai_system_id", "-created_at"],
                "unique_together": {("ai_system", "version_label")},
            },
        ),
    ]
